### ISSUE TITLE
Crash when re-running the FSM Example project

### ISSUE THREAD

**Issue by dithyrambs** [luxkun/ReGoap#34] opened 2018-11-28 05:16 UTC
'Read from location ffffffff caused an access violation' crash error 

This only happens when pressing play for the second, third, and sometimes fourth time, but it always invariably crashes.

[error.log](https://github.com/luxkun/ReGoap/files/2622994/error.log)

**Comment by dithyrambs** [comment] 2018-12-04 07:02
Just found out this crash only happens with multi-threading turned on in the Planner class.

**Comment by luxkun** [comment] 2021-04-04 20:12
Couldn't reproduce, probably fixed by the concurrency fix. Let me know if it still happens for you.

**Closed by luxkun** 2021-04-04 20:12 UTC
